### ISSUE TITLE
過濾收藏數問題

### ISSUE THREAD

**Issue by thorloki4** [FlandreDaisuki/Patchouli#13]
在頁面中收藏數顯示被隱藏，且無法過濾收藏數，即是1以上無任何結果
btw 很棒的工具 謝謝!

**Comment by FlandreDaisuki** [comment]
邪惡的 Pixiv 又改版啦www
等我有空在來改吧 可能要大改了 >_<

**Comment by FlandreDaisuki** [comment]
改好了
版本是 v4.0.0
