### ISSUE TITLE
在"大家的新作品"頁面無法正常使用

### ISSUE THREAD

**Issue by tenninex** [FlandreDaisuki/Patchouli#14]
# Description 問題描述

只能在"關注的新作品"使用，大家的新作品不能顯示圖片

# Environment 環境

作業系統
Windows 10
瀏覽器版本
Chrome 65.0.3325.146 
擴充元件(有啟用的)
Tampermonkey 4.5
Data Saver 2.0.2
uBlock Origin 1.15.2
Image Search Options 0.0.7.4
Free Download Manager Chrome extension 2.1.42
IDM Integration Module 6.30.7

# Debug information 除錯資訊

f12打開web developer tool只有ads報錯，關掉ublock就沒了，不過還是不能顯示圖片

另外感謝開發者，能以收藏數過濾很方便ˊˋ

**Comment by FlandreDaisuki** [comment]
問一下：
1. 不能顯示圖片是指原本存在的圖片也消失，還是沒變化而已 (可以的話截個圖)
2. 你幫我看看這兩個連結 `/mypixiv_new_illust.php` 和 `/new_illust_r18.php`，這兩個網頁處理的方式和 `/new_illust.php`(大家的新作品) 是幾乎一樣的

**Comment by tenninex** [comment]
阿…不好意思，我大概發現原因了
似乎只是因為”大家的新作品”太多，而我搜的又比較冷門，所以抓得比較慢，讓我以為壞了
關鍵字換成東方之類的圖就會跑出來了
不過想請問一下，用”大家的新作品”搜的話速度有點慢 
雖然Patchouli可以用收藏數篩選，但似乎只會篩同一頁的，有辦法讓後面頁數的遞補上來嗎?
例如:目前第一頁超過100收藏的有3張，如果用Patchouli篩100收藏，那第一頁只會顯示三張
，後面的則是要手動翻頁，有可能讓第一頁後超過100收藏的遞補到第一頁嗎?
如果不能或這樣改很麻煩的話也沒關係，我放著讓它自己抓久一點就好了，謝謝你的作品!

從 Windows 10 的郵件傳送

寄件者: Chun-Hao Lien
傳送時間: 2018年3月9日 下午 05:30
收件者: FlandreDaisuki/Patchouli
副本: tenninex; Author
主旨: Re: [FlandreDaisuki/Patchouli] 在"大家的新作品"頁面無法正常使用 (#14)

問一下：
1. 不能顯示圖片是指原本存在的圖片也消失，還是沒變化而已 (可以的話截個圖)
2. 你幫我看看這兩個連結 /mypixiv_new_illust.php 和 /new_illust_r18.php，這兩個網頁處理的方式和 /new_illust.php(大家的新作品) 是幾乎一樣的

**Comment by FlandreDaisuki** [comment]
"大家的新作品" 就是放整個 P 站剛丟上去的作品，除了大手可以幾分鐘內幾百收藏，大部分都是慢慢爬上去的...
所以 "大家的新作品" 其實不適合在一開始就把收藏數調太高。

**Comment by tenninex** [comment]
剛剛整理信箱才發現原來除了close issue以外還有回，不好意思ˊˋ
我知道不能一開始就把收藏數調太高，
不過我發現我想要的功能該怎麼執行了，原來單純調收藏數過濾也是能搜尋的， 
所以我就用pixiv搜尋，再把收藏數提高就好了，我以為一定要有關鍵字才能搜尋，
再次感謝您的作品!!

從 Windows 10 的郵件傳送

寄件者: Chun-Hao Lien
傳送時間: 2018年3月9日 下午 06:00
收件者: FlandreDaisuki/Patchouli
副本: tenninex; Author
主旨: Re: [FlandreDaisuki/Patchouli] 在"大家的新作品"頁面無法正常使用 (#14)

"大家的新作品" 就是放整個 P 站剛丟上去的作品，除了大手可以幾分鐘內幾百收藏，大部分都是慢慢爬上去的...
所以 "大家的新作品" 其實不適合在一開始就把收藏數調太高。
