### ISSUE TITLE
收藏數過濾時可以自訂多個預設值

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Patchouli#16]
像是Tag裡常見的1000、3000、5000、10000這些值
有常用預設值可以選的話，就不用每次都要手動輸入那麼麻煩了

**Comment by FlandreDaisuki** [comment]
你是說書籤數的過濾嗎? hmm 感覺是可以

* 100
* 500
* 1K
* 3K
* 5K
* 10K

大概這六種吧
