### ISSUE TITLE
Chrome上無法正常執行

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Patchouli#18]
用的是暴力猴

![pixiv](https://user-images.githubusercontent.com/12661302/41449126-ca9fea1e-7091-11e8-95bf-be0db37e6dc7.png)

在Firefox上可以正常運作

![screenshot_2018-06-15 pixiv](https://user-images.githubusercontent.com/12661302/41449184-229f2950-7092-11e8-8c4e-f90f30f00bfc.png)

**Comment by FlandreDaisuki** [comment]
我用
* Chrome 67.0.3396.87 (正式版本) (64 位元)
* 暴力猴 2.9.5

可以跑

看你要不要試試安裝 [dev版](https://github.com/FlandreDaisuki/Patchouli/blob/master/dist/patchouli.dev.user.js) (點 Raw 安裝)，會印出更多訊息，把訊息貼上來看看

**Comment by seventhsky** [comment]
我移除後重新安裝就可以正常運作了 可能是舊版升上去時出了問題吧
