### ISSUE TITLE
關於顯示原圖

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/Patchouli#21]
如題
目前顯示原圖在遇到單張圖片的可以正確的得到 `original` 的圖片（高畫質）
但是在遇到多張時只能得到 `master` （壓縮版）

**Comment by maple3142** [comment]
我覺得可以在 BigComponent 那邊遇到 illustPageCount>1 時直接從 urls.original replace 掉 p0 之類的

**Comment by FlandreDaisuki** [comment]
剛剛發現好像全炸了 圖片要帶 Referer ...

**Comment by maple3142** [comment]
url 直接塞 img 應該都要 referer 吧

**Comment by FlandreDaisuki** [comment]
錯的 referer 會導致 403

**Comment by FlandreDaisuki** [comment]
阿 不是這個問題...
是 .jpg 跟 .png 的問題zzz

**Comment by FlandreDaisuki** [comment]
目前是如果首張 `jpg` 就全抓 `jpg`，同理 `png`
不過不確定有沒有混的...

**Comment by FlandreDaisuki** [comment]
畫師朋友說上傳如果有不同 ext 會跳拒絕www
pixiv 做的好！

**Comment by maple3142** [comment]
能顯示正常原圖了，不過我覺得其實不用多一個 request
直接從 url 改就好
https://greasyfork.org/zh-TW/scripts/369789-pixiv-replace-with-original/code#n51

**Comment by FlandreDaisuki** [comment]
真的耶！被以前有的東西誤導了zz
