### ISSUE TITLE
一鍵取消收藏

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/Patchouli#23]
## Is your feature request related to a problem? Please describe. ##
按下愛心是收藏，但是再按一次需要到新分頁才能取消收藏有點麻煩

## Describe the solution you'd like ##
當目前的狀態是已收藏，再按一次就取消收藏

## Describe alternatives you've considered ##
No

**Comment by FlandreDaisuki** [comment]
是可以做
因為我是直接套 pixiv 原本的 script 所以這個邏輯根本不是我寫的www
然後我又很少有取消收藏的需求就沒有特別改

**Comment by FlandreDaisuki** [comment]
其實有[新API](https://github.com/FlandreDaisuki/Patchouli/wiki/New-API#getillustdata)有個 `bookmarkData` 的東西，非 null 即代表有收藏

**Comment by maple3142** [comment]
@FlandreDaisuki 不過這樣取消收藏需要發三次 request...

**Comment by FlandreDaisuki** [comment]
一開始知道狀態了存在 vuex
根據狀態點擊發 `doBookmark` 或 `unBookmark` 就不再確認了，然後**假設成功**並改變 vuex 狀態

目前我 `doBookmark` 也沒有事後做確認

**Comment by FlandreDaisuki** [comment]
這個 API request 小一點
https://github.com/FlandreDaisuki/Patchouli/wiki/New-API#getillustbookmarkdata

**Comment by maple3142** [comment]
不過剛測試了一下，在移除後馬上再去抓一次 `bookmarkData` 會有問題，需要等 1~2 秒才會更新

**Comment by FlandreDaisuki** [comment]
這大概就是 pixiv db 更新的頻率了，無能為力

而且就算真的監控 1~2s 成功失敗再來改狀態
以我來說，不會假設我點下去一到兩秒後失敗了我還繼續盯著或滾回去再加(點)一次
我一定是等下次又搜到這張圖發現還沒加 bookmark 而再加一次
所以我覺得**假設成功**這件事還算符合使用者行為

**Comment by FlandreDaisuki** [comment]
@maple3142 有[新的移除 API](https://github.com/FlandreDaisuki/Patchouli/wiki/New-API#postdeletebookmark) 了

**Comment by maple3142** [comment]
我剛測試了一下沒辦法用 json 傳遞，必須用 `application/x-www-form-urlencoded` 才會成功

除此之外 `postAddBookmark` 和 `postDeleteBookmark` 都能用 `/rpc/index.php` 去呼叫: https://github.com/maple3142/browser-extensions/blob/2c0b3e3403709a6644f05a4f1414eafda9b01123/scripts/pixiv-one-click-bookmark-ex.user.js#L40-L41

**Comment by FlandreDaisuki** [comment]
已更新 wiki (有錯你應該也有權限可以直接改

**Comment by maple3142** [comment]
看起來我是沒辦法編輯的，不過那也沒有什麼錯誤

還有我看我明天幫忙把愛心按鈕一鍵收藏/取消的功能弄好發 PR?

**Comment by FlandreDaisuki** [comment]
可以阿，交給你了

**Comment by maple3142** [comment]
這個應該可以關了
