### ISSUE TITLE
Consider add R18 filter?

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/Patchouli#26]
## Is your feature request related to a problem? Please describe. ##
如題 雖然 pixiv 內建就有 r18 的過濾器了
![image](https://user-images.githubusercontent.com/9370547/43684961-afea3bc0-98dc-11e8-9a1e-fd4816b50463.png)
但是按下那些按鈕還要到新頁面去，需要重新抓一次圖片才行

## Describe the solution you'd like ##
把那三個按鈕移除，然後放在 patchouli 的工具列上面

## Describe alternatives you've considered ##
攔截那三個按鈕的 event，然後按下去會切換 patchouli 的 R18 顯示

## Additional context ##
illustData 中 `xRestrict` 的 0,1,2 分別是普通、R-18、R-18G

**Comment by FlandreDaisuki** [comment]
攔截事件這主意蠻好的

之前我也在想如果有人點下一頁導致 Patchouli 重 load 很浪費頻寬，
但隱藏起來又怪怪的

至於 Patchouli 直接在 tag filter 裡寫 R-18 就可以過濾了，不用加進工具列

**Comment by maple3142** [comment]
可是好像沒辦法用 `!R-18` 之類的來顯示普通的

**Comment by FlandreDaisuki** [comment]
確實 這是之前有想實做的，但這應該另開 issue 討論比較好
我會偏好增強 tag filter 來做到這件事而不是在工具列開選項 (功能正交性)

**Comment by FlandreDaisuki** [comment]
ref: v4.2.0-alpha.13
很髒的 patch 但本來就不在 vue component 的範圍，能動就好
https://github.com/FlandreDaisuki/Patchouli/blob/242df3aede883ea59da138ee18a58adf36fd9c34/src/main.js#L49-L73
