### ISSUE TITLE
Tag filter exclusion

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/Patchouli#27]
## Is your feature request related to a problem? Please describe. ##
#26 談到說可以用 `R-18` 之類的來指定要顯示 R18 作品，但目前還沒有方法類似 `!R-18` 之類的來排除特定 tag

## Describe the solution you'd like ##
`!tag` 或是 `~tag` 或其他的方法來排除 tag

## Describe alternatives you've considered ##
把 tag filter 弄成可以吃一些 expression 之類的，例如 `tag1 && !tag2 && (tag3 || tag4)`，功能更強大也更複雜

## Additional context ##
不曉得有哪些字元是 pixiv tag 的合法字元

**Comment by FlandreDaisuki** [comment]
這邊有一個關鍵的問題點，
如果一個包含 include 和 exclude 條件的結果，到底要顯示還是隱藏
- - -
除了空白是 seperator 之外都是合法字元的樣子

**Comment by maple3142** [comment]
同時 include 和 exclude 就丟 error 出來吧

**Comment by maple3142** [comment]
我是覺得 tag 應該要改為嚴格比對，而不是用 regex 來 match
像是 `abc` 不會 match 到 `abc・def`，這樣的話就沒有這種問題了

**Comment by FlandreDaisuki** [comment]
可是這樣我覺得會比現在的難用，像我本命的 tag 就會變成 `フランドール・スカーレット`
但我現在是打 `フラン` 就好了

**Comment by maple3142** [comment]
`tag` -> `tagstr.includes('tag')`
`!tag` -> `!tagstr.includes('tag')`
`tag1 && !tag2` -> `tagstr.includes('tag1')&&!tagstr.includes('tag2')`

所以 `!(fate) && ジャンヌ` 在 match `ジャンヌ・ダルク(Fate)` 的時候是不包含的

而符號可以用像是 `"ジャンヌ・ダルク(Fate)"` 來處理，不過不曉得這對一個 user.js 是不是有點複雜

**Comment by FlandreDaisuki** [comment]
主要是不確定有沒有 tag 是包含 `"`/`!` (合法字元) 的，有的話還是會有問題

**Comment by FlandreDaisuki** [comment]
被收進 pixiv 百科的直接 out 了

[!!!カオスタイム!!!](https://dic.pixiv.net/a/!!!カオスタイム!!!)
[~で愛してあげようか](https://dic.pixiv.net/a/~で愛してあげようか)
[!](https://dic.pixiv.net/a/!) [\[](https://dic.pixiv.net/search?query=[) [\^](https://dic.pixiv.net/search?query=^) [\*](https://dic.pixiv.net/search?query=*) [\&](https://dic.pixiv.net/search?query=&) [\:](https://dic.pixiv.net/search?query=:) [\;](https://dic.pixiv.net/search?query=;) [\(](https://dic.pixiv.net/search?query=%28)

- - -
這幾個比較能用
[`"`](https://dic.pixiv.net/search?query=")
[`{`](https://dic.pixiv.net/search?query={)
[`+`](https://dic.pixiv.net/search?query=+)
[`-`](https://dic.pixiv.net/search?query=-)

根據以上符號比較可行的作法是：
空白：seperator 表 "且"
{}：scope 符號，功能同數學的 ()
空白||空白：seperator 表 "或"
prefix `+`(可省略)：顯示部份搜尋
prefix `++`：顯示準確搜尋
prefix `-`：隱藏部份搜尋
prefix `--`：隱藏準確搜尋

`(A && B) || (!C && !D)` => `{A B} || {-C -D}`
`!(fate) && ジャンヌ` => `ジャンヌ -fate`

**Comment by maple3142** [comment]
`&&` 我覺得可以當作選擇性的，只有 `||` 卻沒有 `&&` 有點奇怪
而且 [&](https://dic.pixiv.net/search?query=&) 是沒有搜尋結果的

**Comment by FlandreDaisuki** [comment]
我寫好部份了，在 [`4.2.x/src/lib/tagMatcher.js`](https://github.com/FlandreDaisuki/Patchouli/blob/4.2.x/src/lib/tagMatcher.js)
測試在 [`4.2.x/test/tagMatcher.js`](https://github.com/FlandreDaisuki/Patchouli/blob/4.2.x/test/tagMatcher.js)

目前**為了效能**，我 tag 都先 cancat 起來了，所以比較難實現 `++` 跟 `--` (不管是 `split('\x00')` 或是 `match`, 都不太合適。前者是要對極大量的 tag 大量重配記憶體 immutable String → mutable Array；後者是合法字元裡要處理 RegExp 保留字)，目前有什麼值得測試的就 pr 到 `4.2.x` 或直接留言吧

然後我 wiki 開了所有權限，到時可能還要寫個 tag filter 教學 Orz

**Comment by maple3142** [comment]
看了一下 test 應該都沒問題，不過實際用起來好像怪怪的
![image](https://user-images.githubusercontent.com/9370547/44617718-8be0de00-a89a-11e8-8ac9-1970f971ac2a.png)

然後 `-` 好像有點怪怪的 (下面的圖片都是 NSFW)
[none](https://user-images.githubusercontent.com/9370547/44617776-abc4d180-a89b-11e8-8d43-b76ef0c244a9.png)
[inclusion](https://user-images.githubusercontent.com/9370547/44617756-5983b080-a89b-11e8-886a-3719406d6925.png)
[exclusion](https://user-images.githubusercontent.com/9370547/44617769-8fc13000-a89b-11e8-99f5-8409112f21bc.png)

**Comment by maple3142** [comment]
原來是還沒測試==
不過我覺得 test 可以加入一些特殊字元的 rule 進去測試
例如: `-R-18` `aaa&bbb` 之類的...

**Comment by FlandreDaisuki** [comment]
嗯嗯 目前也有個限制，`{}` 不能疊到第二層ww
`{A && B} || {C}` -- OK
`{{A && B} || C}` -- G_G

**Comment by FlandreDaisuki** [comment]
目前的實做的 README
https://github.com/FlandreDaisuki/Patchouli/wiki/Tag-Filter-Expression-Usage

建立在使用者不會下太複雜的 tag filter，這樣應該很夠用了

有 operator 的測試加進去了

**Comment by FlandreDaisuki** [comment]
v4.2.0-alpha.12 Add tagFilterQuerier
剛剛試了下 效果還算不錯 😀

https://github.com/FlandreDaisuki/Patchouli/tree/4.2.x/dist
