### ISSUE TITLE
繪師作品頁面功能失效

### ISSUE THREAD

**Issue by thorloki4** [FlandreDaisuki/Patchouli#28]
## Describe the bug ##
A clear and concise description for what the bug happens on which page.
盡可能描述在哪個頁面執行什麼動作發生的 bug。

繪師作品頁面改版導致功能失效。
https://www.pixiv.net/member_illust.php?id=xxxxxx

## Environment ##
 - Browser: chrome 68.0.3440.106 64bit
 - Script Manager: Tampermonkey

## Debug messages ##
You can install `dist/patchouli.dev.user.js`, open the console, and paste as more debug messages as you can see when the bug happens to help us find the error faster.
你可以安裝 `dist/patchouli.dev.user.js`，打開主控台並貼上出現 bug 時的錯誤訊息或除錯訊息，越多線索可以讓我越快找到問題並修復之。

<details close>

```
 TypeError: Cannot read property 'classList' of null (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:4)
    at C.prepareMountPoint (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:616)
    at eval (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:17)
    at eval (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:17)
    at Array.forEach (<anonymous>)
    at eval (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:17)
    at C._withCommit (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:17)
    at C.commit (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:17)
    at C.commit (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:17)
    at eval (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:3419)
    at Window.tms_05c82441_07a6_4859_88ca_b4df32aec708 (userscript.html?id=05c82441-07a6-4859-88ca-b4df32aec708:3504)
```

</details>

**Comment by FlandreDaisuki** [comment]
@maple3142 看起來你的還沒被改版
![_001](https://user-images.githubusercontent.com/5981459/44041364-32ec63d0-9f50-11e8-8e34-4f28acbffc28.png)

@thorloki4  既然有的有被改版有的人沒有，我可能等 pixiv 公佈全面更新完成再來改這個，除了新版型要研究一下之外，我最近也比較忙

**Comment by thorloki4** [comment]
好的 感謝~

**Comment by FlandreDaisuki** [comment]
ref: [pixiv的個人首頁將全新改版](https://www.pixiv.net/info.php?id=4704)

新版我已經完成八成的改版了，不相容於舊版頁面
晚點會釋出 alpha 版，還請多幫忙抓錯 🙇🙇

**Comment by FlandreDaisuki** [comment]
@thorloki4 試試看吧
https://github.com/FlandreDaisuki/Patchouli/tree/4.2.x/dist

**Comment by thorloki4** [comment]
功能可以正常運作了 非常謝謝! 不好意思這麼久才回復。
另外圖片連結的點擊過和沒點過都是相同顏色，對我有些不方便，請問能自行修改的地方嗎?

**Comment by FlandreDaisuki** [comment]
@thorloki4 
我寫了個 usercss 你裝一下就可以自訂顏色了
https://gist.github.com/FlandreDaisuki/c8835fe6cf21e4dbc459238685d2a258

因為 pixiv 故意不改變顏色，對我來說也沒什麼影響，所以也不打算寫進去 Patchouli 裡面
如果你懂點 CSS 的話可以自己增加樣式

**Comment by thorloki4** [comment]
好的，還特別幫我解決問題 非常感謝~

**Comment by seventhsky** [comment]
了解 已經裝上 pre-release 版 順便回報一個bug

![- pixiv](https://user-images.githubusercontent.com/12661302/45473526-e36fbc80-b769-11e8-8203-aa27ef718cc0.png)

新加關注時那條bar會變成這樣子XD

**Comment by FlandreDaisuki** [comment]
@seventhsky 回報 bug 另開一個 issue 吧
環境那些順便

**Comment by maple3142** [comment]
看來只有我還是舊版介面...? 不曉得什麼時候會改版完成

**Comment by FlandreDaisuki** [comment]
上次作品頁我是公布全面更新完成的前一天才被改ww

根據上次的更新時程，大概要到十月多了吧

**Comment by FlandreDaisuki** [comment]
/* murmur */
都還沒改完就[開新坑](https://www.pixiv.net/info.php?id=4796) pixiv 這樣沒問題嗎 Orz

**Comment by maple3142** [comment]
Patchouli 不是原本就沒有支援小說的嗎?

除此之外我剛發現我的也已經被改版了

**Comment by FlandreDaisuki** [comment]
是沒有，只是他們這樣不知道是因為可以獨立部屬還是...

我之前在個人頁有抓到一個 bug：
個人頁收藏點進去公開是顯示公開書籤，但點非公開會變成非公開的小說收藏

我怕他也會改到個人頁這邊來... // v4.2.0 還沒正式發布就要又改版，很氣

**Comment by FlandreDaisuki** [comment]
[個人首頁設計更新已完成](https://www.pixiv.net/info.php?id=4812)
收工！！
