### ISSUE TITLE
黑名單 (不使用) 頁面清單

### ISSUE THREAD

**Issue by bestpika** [FlandreDaisuki/Patchouli#29]
## Is your feature request related to a problem? Please describe. ##

- 部分頁面不想使用但是沒辦法個別關閉

## Describe the solution you'd like ##

- 希望能夠增加一個 list 讓我設定不使用的頁面網址 (regex)

## Describe alternatives you've considered ##

- 目前無替代方案，只能不用的時候整個 script 關掉

**Comment by FlandreDaisuki** [comment]
我在想這個應該可以用腳本管理器的方法來解決。

- - -

以 Violentmonkey 來說：
<details>

<summary>編輯 → 設定 → <code>@exclude</code>規則</summary>

![_001](https://user-images.githubusercontent.com/5981459/45924502-04879880-bf34-11e8-8b6a-bbd8f0706df4.png)

</details>

- - -

以 Tampermonkey 來說：
<details>

<summary>點名稱編輯 → 設置 → 自訂 excludes</summary>

![_002](https://user-images.githubusercontent.com/5981459/45924511-8a0b4880-bf34-11e8-9c3b-29a701d97fa5.png)

</details>

**Comment by FlandreDaisuki** [comment]
@bestpika 我試了一下覺得腳本管理器的方法不錯
而且有支援 glob，更新也不會消失
除非有特別的頁面需要，不然應該就會是這樣解了
