### ISSUE TITLE
按停的時候不會真的停止

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Patchouli#3]
如題 當我想停止繼續過濾的時候 它還是會繼續跑
另外可以不要預先處理一開始的圖片嗎？
每次圖片都要先消失那麼一下還挺煩人的

**Comment by FlandreDaisuki** [comment]
對 按停的時候不會真的停止
因為我實作上跟之前的不太一樣，比較陽春w

圖片消失一下的問題應該比較好解決
等我有空會改掉
