### ISSUE TITLE
New Pixiv Profile Design

### ISSUE THREAD

**Issue by Spyroflex** [FlandreDaisuki/Patchouli#36]
## Is your feature request related to a problem? Please describe. ##
It doesn't work with the new Profile Design they introduced, which doesn't even show the number of bookmarks now and the tag selection has no english translation, 
so this tool is kinda important to have here.

## Describe the solution you'd like ##
Having it work just like before. Probably not a simple fix tho.

## Describe alternatives you've considered ##
Another way would be with the pixiv search engine to somehow enable the search of all the works from a specific artist. 

## Additional context ##
-

**Comment by FlandreDaisuki** [comment]
Hello, what the version of Patchouli you use? What is your OS and browser?
It works in `v4.2.0-alpha.20` in both my latest Chrome and Firefox and both my Windows and Linux.

I released the alpha version and explained the reason in [README](https://github.com/FlandreDaisuki/Patchouli/blob/master/README.en.md#introduction)

You can also check the [README of v4.2.0](https://github.com/FlandreDaisuki/Patchouli/blob/4.2.x/README.en.md)

**Comment by Spyroflex** [comment]
Ok I checked again, and it was just my mistake, apparently a new browser extension I installed interfered... everything works fine now. So yea, thanks anyway
