### ISSUE TITLE
無法正常顯示縮圖

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Patchouli#4]
原因不明 只要腳本開著就會看不到縮圖
![2](https://cloud.githubusercontent.com/assets/12661302/21492855/fd9d1382-cc42-11e6-827e-5b478046f666.png)
![3](https://cloud.githubusercontent.com/assets/12661302/21492858/fdb0b5ea-cc42-11e6-8308-7d7e11f24f19.png)
![4](https://cloud.githubusercontent.com/assets/12661302/21492857/fda601f4-cc42-11e6-8663-ca83c8d0e3ff.png)

**Comment by FlandreDaisuki** [comment]
改用 MK-II 吧
知道問題點在哪但改起來太麻煩 Q_Q
