### ISSUE TITLE
No page numbers to click on on new profiles

### ISSUE THREAD

**Issue by gwj27481** [FlandreDaisuki/Patchouli#41]
## Describe the bug ##

As the title says, there are no page numbers to click on on the new profile designs, on any tab.

## Steps to reproduce ##

Go to a profile page on any tab, scroll down, no page numbers to click on.

## Screenshots ##

![image](https://user-images.githubusercontent.com/50501757/59450754-3b774480-8e0a-11e9-82a8-ab991a094c06.png) (script off)

![image](https://user-images.githubusercontent.com/50501757/59450804-51850500-8e0a-11e9-9914-7ff4ae1f9301.png) (script on)

of course this happens on tabs with multiple pages too.

## Environment ##

Windows 10
Firefox 67.0.2 64-bit
Tampermonkey
Version 4.2.2

**Comment by FlandreDaisuki** [comment]
Thanks your feedback first.

Actually, this is not a bug. The usage of Patchouli doesn't need pagination.
If I add pagination as its function, it will be confused that click **Go** to find before or after current page.
So, if you like pagination-based navigation to browse images, Patchouli maybe not a good tool for you.

**Comment by gwj27481** [comment]
Was this changed recently? I used to have pages on search pages. I would like to have both infinite loading and pages.

**Comment by FlandreDaisuki** [comment]
No. 
The last time I change the code is https://github.com/FlandreDaisuki/Patchouli/commit/312db4592cdbd56199f3982df249c8fac205f5d2 , in 2019/1/10, v4.2.2.

OK, I'll take a look about this issue.

**Comment by FlandreDaisuki** [comment]
I test following urls, which is the page link you click:

+ https://www.pixiv.net/member_illust.php?id=7463&type=illust
+ https://www.pixiv.net/member_illust.php?id=7463&type=illust&p=3
+ https://www.pixiv.net/member_illust.php?id=7463&type=illust&p=999

When Patchouli turns on, it shows the same results. I don't know whether your pixiv will show the same results.
+ If it's the same, that the pagination is meaningless.
+ If not, I can't reproduce this bug on my machine, maybe pixiv is doing some testing on your account.

**Comment by gwj27481** [comment]
I recently switched from Greasemonkey with a good amount of extra pixiv userscripts to Tampermokey with just Patchouli. That could be why pages behaved differently before. 

I tried the links and got the same results. In any case I personally found numbered pages easier to navigate, especially for profiles with a lot of content. I will continue using Patchouli regardless so consider it a suggestion.
