### ISSUE TITLE
Userscript breaks youtube videos in fanbox pages

### ISSUE THREAD

**Issue by b1116490** [FlandreDaisuki/Patchouli#44]
## Describe the bug ##

As the title says, videos don't appear on fanbox pages when the script is on.

## Steps to reproduce ##

1. Go to https://www.pixiv.net/fanbox/creator/34731446
2. Click on a video
3. See nothing

## Screenshots ##

![image](https://user-images.githubusercontent.com/51966907/61578175-279ebc80-aaf3-11e9-835d-5105dced62a7.png)
。

## Environment ##

- OS: W10
- Browser: Firefox 68.0.1 64 bits
- Script Manager: Tamper
- Version: 4.9.5941

**Comment by FlandreDaisuki** [comment]
#43 pointed the cause.
You can try to solve this by add meta in script header or wait the next version.

```
// @exclude           *://www.pixiv.net/fanbox/*
```

**Comment by FlandreDaisuki** [comment]
v4.2.3 fixed
