### ISSUE TITLE
Patchouli stopped working ~2 days ago

### ISSUE THREAD

**Issue by seascape** [FlandreDaisuki/Patchouli#49]
**Describe the bug**

I noticed Patchouli stopped working approximately two days ago. It simply doesn't do anything on Illustration, Manga or Bookmark pages.

It does still load in search pages. For example:
https://www.pixiv.net/search.php?word=Fate%2FGrandOrder&s_mode=s_tag_full

**Steps to reproduce**

1. Go to a Pixiv artist gallery page such as 
https://www.pixiv.net/member_illust.php?id=#######&type=illust
2. Observe that Patchouli doesn't appear to load or otherwise do anything visible.

**Environment**

Windows 10 / Firefox 70.0.1 / Violentmonkey / Patchouli v4.2.4

I attempted to use Patchouli with Firefox/Greasemonkey, Firefox/FireMonkey, and Chrome/Violentmonkey with the same result.

**Debug messages**

"You can install `dist/patchouli.dev.user.js`, open the console, and paste as more debug messages as you can see when the bug happens to help us find the error faster."

Tried this; that script also had no visible result.

Could this breakage be related to #48 or another existing issue?

</details>

**Comment by FlandreDaisuki** [comment]
Yes, this issue is related to #48 .
