### ISSUE TITLE
MK-II 版沒有評分過濾功能

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Patchouli#5]
依作者回應改用MK-II 版
但MK-II 版看不到評分過濾功能？
是本來就沒有嗎？

**Comment by FlandreDaisuki** [comment]
對，因為書籤數感覺比較正相關，所以用書籤數來取代相似的功能
而且那個地方可以用滑鼠滾輪來++，也可以用打字的，我覺得比較方便 :sunglasses:

**Comment by seventhsky** [comment]
因為我一直是書籤、評分並用來過濾的所以不太習慣
可以考慮加一下嗎XD

**Comment by FlandreDaisuki** [comment]
我想，下面這個結果還蠻明顯的了
基本上評分跟書籤數大約是10 : 1
所以應該不會去加評分過濾功能了 (顯示就留著好了)

![rating_score_and_bookmark](https://cloud.githubusercontent.com/assets/5981459/23372737/db227e28-fd57-11e6-8b7c-a7ff27c72571.png)
