### ISSUE TITLE
作者頁失效

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Patchouli#50]
## Describe the bug ##

https://www.pixiv.net/member_illust.php?id=9930155
沒有顯示過濾介面

## Screenshots ##

![www pixiv net_member php_id=9930155](https://user-images.githubusercontent.com/12661302/68542345-c2930d80-03e6-11ea-9f08-970ac6cc4fab.png)

## Environment ##

Windows 10
Microsoft Edge 79.0.309.15 beta / Firefox 71.0b7
Violentmonkey
v4.2.4

## Debug messages ##

You can install `dist/patchouli.dev.user.js`, open the console, and paste as more debug messages as you can see when the bug happens to help us find the error faster.
你可以安裝 `dist/patchouli.dev.user.js`，打開主控台並貼上出現 bug 時的錯誤訊息或除錯訊息，越多線索可以讓我越快找到問題並修復之。

<details close>

```
Paste here. 貼在這裡。
```

</details>

**Comment by FlandreDaisuki** [comment]
這樣應該就可以了，試試看ㄅ

ok 的話回報一下我可以關 issue

**Comment by seventhsky** [comment]
已經修好沒問題了 Thanks
