### ISSUE TITLE
安裝完卻沒有出現工具列?

### ISSUE THREAD

**Issue by wolf98139** [FlandreDaisuki/Patchouli#56]
## Describe the bug ##

A clear and concise description for what the bug happens on which page.
盡可能描述在哪個頁面執行什麼動作發生的 bug。

## Screenshots ##

如果有截圖也可以貼上來。

## Environment ##

- OS: [e.g. Windows 10, Linux Mint 18.03]
- Browser: [e.g. chrome 66.0.3359.139 64bit, firefox 60.0 64bit]
- Script Manager: [e.g. Tampermonkey, Violentmonkey]
- Version: [e.g. v4.0.6]

## Debug messages ##

You can install `dist/patchouli.dev.user.js`, open the console, and paste as more debug messages as you can see when the bug happens to help us find the error faster.
你可以安裝 `dist/patchouli.dev.user.js`，打開主控台並貼上出現 bug 時的錯誤訊息或除錯訊息，越多線索可以讓我越快找到問題並修復之。

<details close>

```
Paste here. 貼在這裡。
```

</details>
 Tampermonkey有開啟腳本,卻沒有影片中的搜尋功能,

**Comment by FlandreDaisuki** [comment]
#48
