### ISSUE TITLE
在收藏畫面中會把選擇框吃掉

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Patchouli#8]
如標題
在收藏畫面裡每張圖都會有個小方框
是用來整理你的收藏的
啟用腳本的話這方框會被吃掉選不了

**Comment by FlandreDaisuki** [comment]
這個我知道 :sweat_smile: 
但是還沒想到好辦法解決，目前可能先取消腳本來整理會好一點 :upside_down_face:
